name: JavaScript workflow

on: [push]

jobs: 
  test: 
    runs-on: ubuntu-latest


    steps: 
    - users: actions/checkout@1
    - name: Use Node.js 12.X
      uses: actions/setup-node@v1
      with: 
        node-version: "12.x"
    -name: npm install, and test 
      run: 
        npm install
        npm test
      env: 
        CI: true